# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
executors:
  default_image:
    docker:
    - image: cimg/python:3.10
jobs:
  build:
    docker:
    - image: cimg/python:3.10
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  install-pluton-kit:
    #executor: default_image
    docker:
    - image: cimg/python:3.10
    resource_class: large
    steps:
    - checkout
    - run:
        name: Add submodule to custom folder
        command: |
          if [ ! -d "./script/package/pluton-kit" ]; then
            git submodule add -b feature/1.0.32a1/draft-enhancement --name pluton-kit https://github.com/fonipts/pluton-kit.git ./script/package/pluton-kit
          fi
          git submodule update --init --recursive
    - run:
        name:  Init pip package
        command: |
          python -m pip install --upgrade pip
          cd ./script/package/pluton-kit
          pip install -e .
          pip install -r requirements.txt
    - run:
        name:  Flask 1
        command: |
          cd ./test
          python ../script/cmd.py flask1
    - run:
        name:  Flask 2
        command: |
          cd ./test
          python ../script/cmd.py flask2
    - run:
        name:  Bottle 1
        command: |
          cd ./test
          python ../script/cmd.py bottle1     
  install-pluton-kit2:
    #executor: default_image
    docker:
    - image: cimg/python:3.10
    resource_class: large
    steps:
    - checkout                                 
    - run:
        name:  FastAPI
        command: |
          cd ./test
          python ../script/cmd.py fastapi1
          pkill -f "uvicorn" || true
    - run:
        name:  FastAPI 2
        command: |
          cd ./test
          python ../script/cmd.py fastapi2
          pkill -f "uvicorn" || true
    - run:
        command: |
          cd ./test
          python ../script/cmd.py django1
    - run:
        name: Clean bluprint test folder
        command: |
          rm -rf ./test/*        
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  CI_CD_Tests:
    jobs:
    - build
  Install_Pluton_Kit:
    jobs:
    - install-pluton-kit
    - install-pluton-kit2
